LoopKit/Loop

- Loop/Base.lproj/Main.storyboard
- Loop/Managers/DeviceDataManager.swift
- Loop/Managers/LoopDataManager.swift
> Move device-specific waiting logic out of LoopDataManager

- Loop.xcodeproj/project.pbxproj
- Loop/Base.lproj/Main.storyboard
- Loop/Extensions/NSUserDefaults.swift
- Loop/Managers/DeviceDataManager.swift
- Loop/Managers/WatchDataManager.swift
- Loop/Models/InsulinDataSource.swift
- Loop/View Controllers/SettingsTableViewController.swift
- Loop/Views/SegmentedControlTableViewCell.swift
> Adding a new setting for preferred insulin data source

- Loop/Extensions/NSUserDefaults.swift
> Fixing unpersisted insulin data source preference

- Loop/Managers/DeviceDataManager.swift
> Read glucose + pump data deterministically for x22 + G4 Share users

- Loop/View Controllers/BolusViewController.swift
- Loop/View Controllers/StatusTableViewController.swift
> Fixing the transition state to Carb and Bolus entry view controllers

- Loop.xcodeproj/project.pbxproj
- Loop/Base.lproj/Main.storyboard
- Loop/Managers/StatusChartManager.swift
- Loop/Models/Glucose.swift
- Loop/Models/GlucoseG4.swift
- Loop/Models/MySentryPumpStatusMessageBody.swift
- Loop/Models/SensorDisplayable.swift
- Loop/View Controllers/StatusTableViewController.swift
- Loop/Views/BasalRateHUDView.swift
- Loop/Views/GlucoseHUDView.swift
and displaying the last glucose value in a HUD view
> Graphing glucose using the system's preferred unit

- Loop/Base.lproj/Main.storyboard
- Loop/Extensions/DoseStore.swift
- Loop/Managers/DeviceDataManager.swift
> Saving pump history into LoopKit and delegating upload to Nightscout

- Loop/Managers/LoopDataManager.swift
> Prevent recommending a temp basal right after a bolus was set

- Loop/Base.lproj/Main.storyboard
- Loop/Managers/StatusChartManager.swift
- Loop/View Controllers/PredictionTableViewController.swift
- Loop/View Controllers/StatusTableViewController.swift
- Loop/Views/ChartTableViewCell.swift
* Graph titles
* Almost always display axes, regardless of empty data.
> Minor chart improvements

- Loop.xcodeproj/project.pbxproj
- Loop/Base.lproj/Main.storyboard
- Loop/Extensions/CollectionType.swift
- Loop/Extensions/UIColor.swift
- Loop/Managers/StatusChartManager.swift
- Loop/View Controllers/PredictionTableViewController.swift
- Loop/View Controllers/StatusTableViewController.swift
- Loop/Views/ChartContentView.swift
- Loop/Views/ChartPointsScatterDownTrianglesLayer.swift
- Loop/Views/ChartPointsTouchHighlightLayerViewCache.swift
- Loop/Views/ChartTableViewCell.swift
- Loop/Views/TitleSubtitleTableViewCell.swift
- New labels that highlight eventual glucose, current IOB, total delivery, and COB
- Fixes #159
- Dynamic selection of graph history length based on available display with. Rotate landscape to see more data.
- New treatment for the recommended temp cell
> Graph improvements

- Loop/Base.lproj/Main.storyboard
- Loop/Models/Glucose.swift
- Loop/Models/GlucoseG4.swift
- Loop/Models/MySentryPumpStatusMessageBody.swift
- Loop/Models/SensorDisplayable.swift
- Loop/Models/ShareGlucose+GlucoseKit.swift
- Loop/View Controllers/PredictionTableViewController.swift
- Loop/Views/GlucoseHUDView.swift
> Displaying an indicator for glucose values downloaded from Share

- Loop/Managers/DeviceDataManager.swift
- Loop/View Controllers/SettingsTableViewController.swift
- Loop/View Controllers/StatusTableViewController.swift
- Loop/Views/AuthenticationTableViewCell.xib
- Loop/Views/BasalRateHUDView.swift
- Loop/Views/BatteryLevelHUDView.swift
- Loop/Views/ChartTableViewCell.swift
- Loop/Views/GlucoseHUDView.swift
- Loop/Views/HUDView.swift
- Loop/Views/LoopCompletionHUDView.swift
- Loop/Views/ReservoirVolumeHUDView.swift
- Loop/Views/SwitchTableViewCell.swift
- WatchApp Extension/Controllers/AddCarbsInterfaceController.swift
- WatchApp Extension/Controllers/BolusInterfaceController.swift
- WatchApp Extension/Controllers/StatusInterfaceController.swift
Moving most outlets to weak references
Adding a note about improving reliability of wakeup on constrained devices
> Preventing truncation of insulin action duration (Fixes #213)

- README.md
Button was linked to LoopKit/LoopKit instead of the correct LoopKit/Loop
Thanks to @ldunn12 for the heads-up!
> Fix Gitter Button

- Loop.xcconfig
Docs should be updated to reflect this change.
> Update bundle identifier to com.loopkit

- Loop Status Extension/Info.plist
- Loop Status Extension/StatusExtensionContext.swift
- Loop/Managers/DeviceDataManager.swift
- Loop/Managers/StatusExtensionDataManager.swift
Also bumping status extension version up to 1.2.0
> adding CustomDebugStringConvertible support for status extension manager

- LoopUI/Views/LoopStateView.swift
> Use a clear fill color for the circle.

- Loop.xcodeproj/project.pbxproj
- Loop.xcodeproj/xcshareddata/xcschemes/Complication - WatchApp.xcscheme
- Loop.xcodeproj/xcshareddata/xcschemes/DoseMathTests.xcscheme
- Loop.xcodeproj/xcshareddata/xcschemes/Loop Status Extension.xcscheme
- Loop.xcodeproj/xcshareddata/xcschemes/Loop.xcscheme
- Loop.xcodeproj/xcshareddata/xcschemes/LoopTests.xcscheme
- Loop.xcodeproj/xcshareddata/xcschemes/Notification - WatchApp.xcscheme
- Loop.xcodeproj/xcshareddata/xcschemes/WatchApp.xcscheme
Signing frameworks at build time is not recommended so
disable code signing for LoopUI. All changes performed automatically by
XCode
> Upgrade project to 0820

- Loop.xcodeproj/project.pbxproj
- Loop/Extensions/NSUserDefaults.swift
- Loop/Managers/DeviceDataManager.swift
- Loop/Models/EnliteSensorDisplayable.swift
- Loop/View Controllers/SettingsTableViewController.swift
- LoopUI/Models/SensorDisplayable.swift
> Tmecklem x22 enlite cgm

- Loop.xcodeproj/project.pbxproj
- Loop/Base.lproj/Main.storyboard
- Loop/Extensions/CaseCountable.swift
- Loop/Extensions/DoseStore.swift
- Loop/Extensions/GlucoseRangeSchedule.swift
- Loop/Extensions/NSUserDefaults.swift
- Loop/Managers/AnalyticsManager.swift
- Loop/Managers/DeviceDataManager.swift
- Loop/Managers/KeychainManager.swift
- Loop/Managers/LoopDataManager.swift
- Loop/Managers/StatusExtensionDataManager.swift
- Loop/Managers/WatchDataManager.swift
- Loop/Models/GlucoseThreshold.swift
- Loop/Models/LoopSettings.swift
- Loop/Models/NetBasal.swift
- Loop/Models/Result.swift
- Loop/View Controllers/CommandResponseViewController.swift
- Loop/View Controllers/PredictionTableViewController.swift
- Loop/View Controllers/SettingsTableViewController.swift
- Loop/View Controllers/StatusTableViewController.swift
- LoopTests/KeychainManagerTests.swift
- WatchApp Extension/ExtensionDelegate.swift
- Adjusts responsibilities of DeviceDataManager and LoopDataManager:
- DeviceDataManager coordinates communication with devices and plugins
- LoopDataManager manages stored data and algorithms
> Loop data manager refactor

- Loop/Models/ServiceAuthentication/AmplitudeService.swift
- Loop/Models/ServiceAuthentication/LogglyService.swift
- Loop/Models/ServiceAuthentication/MLabService.swift
- Loop/Models/ServiceAuthentication/NightscoutService.swift
- Loop/Models/ServiceAuthentication/ServiceCredential.swift
- Loop/Models/ServiceAuthentication/ShareService.swift
> Fix share server select issue

- Loop.xcodeproj/project.pbxproj
> Update the Carthage script to specify output files

- Loop/Info.plist
adding to info.plist to allow for face ID authentication
> fix for face-id authentication on bolusing

- Loop/View Controllers/CarbAbsorptionViewController.swift
- Loop/View Controllers/ChartsTableViewController.swift
- Loop/View Controllers/InsulinModelSettingsViewController.swift
- Loop/View Controllers/PredictionTableViewController.swift
- Loop/View Controllers/SettingsTableViewController.swift
- Loop/View Controllers/StatusTableViewController.swift
> Track changing units in charts

- Loop/Managers/DeviceDataManager.swift
- Loop/Managers/LoopDataManager.swift
- Loop/Models/LoopError.swift
> Localize loop error messages

- DoseMathTests/de.lproj/Localizable.strings
- Loop/de.lproj/InfoPlist.strings
- Loop/de.lproj/Localizable.strings
- Loop/de.lproj/Main.strings
Some German strings in Loop were wrong or at least not a good translation - fixed this. Request to merge into master.
> Corrected German localizable strings

- Loop.xcodeproj/project.pbxproj
> Watch series 0 fix

- Common/Models/PumpManagerUI.swift
- Loop/Managers/DeviceDataManager.swift
- Loop/View Controllers/StatusTableViewController.swift
add a backoff for heartbeat enabling, and fix a bug in pump manager observation registration
> Tweaks to device manager

- Loop/Info.plist
https://github.com/LoopKit/Loop/issues/1118
> NSBluetoothAlwaysUsage for Omnipod-testing

- Loop.xcodeproj/project.pbxproj
- LoopCore/LoopSettings.swift
- WatchApp Extension/Controllers/AddCarbsInterfaceController.swift
- WatchApp Extension/Controllers/BolusInterfaceController.swift
- WatchApp Extension/ExtensionDelegate.swift
- WatchApp Extension/Extensions/NumberFormatter+WatchApp.swift
- WatchApp Extension/Extensions/UIColor.swift
- WatchApp Extension/Extensions/WKInterfaceLabel.swift
- WatchApp Extension/Scenes/BolusConfirmationScene.swift
- WatchApp/Base.lproj/Interface.storyboard
> Add confirmation for watch bolus, and start at full recommendation.

- LoopUI/Views/GlucoseHUDView.swift
fresh base for @erikdi work at https://github.com/LoopKit/Loop/pull/709
> display - for HUD CGM when value is >15 min old

- Common/es.lproj/Intents.strings
- Common/es.lproj/Localizable.strings
- Learn/es.lproj/Main.strings
- Loop Status Extension/es.lproj/Localizable.strings
- Loop/es.lproj/Localizable.strings
- Loop/es.lproj/Main.strings
- LoopUI/es.lproj/Localizable.strings
- WatchApp Extension/es.lproj/Localizable.strings
- WatchApp/es.lproj/Interface.strings
I updated the Spanish translations to cover new strings that were added, like those from overrides and the new unified carb entry flow.
> Update Spanish translations

- Common/fr.lproj/Localizable.strings
- Learn/fr.lproj/Localizable.strings
- Loop/fr.lproj/Localizable.strings
- Loop/fr.lproj/Main.strings
- WatchApp/fr.lproj/Interface.strings
I updated the French translations due to the new unified carb entry flow.
> Update French translations

- Loop/Managers/LoopDataManager.swift
- Loop/Managers/NightscoutDataManager.swift
- Loop/Managers/StatusExtensionDataManager.swift
Use prediction that includes pending insulin in:
* Nightscout uploads
* Issue Report
* Status Extension
> Use prediction that includes pending insulin

- WatchApp Extension/Views/Carb Entry & Bolus/CarbAndBolusFlow.swift
- WatchApp Extension/Views/Extensions/Environment+SizeClass.swift
> Add handling for 45mm and 41mm watches

- Loop/Managers/LoopDataManager.swift
When the forecast changes, make a new dosing decision (without actually looping), and store for external clients.
> Create new dosing decision after forecast change, for external clients

- Loop/View Models/BolusEntryViewModel.swift
Fixes https://github.com/LoopKit/Loop/issues/1641
> Fetch settings before updating forecast, and respond to changed settings

- Loop/Managers/LoopDataManager.swift
Insulin effects were being fetched and filtered using the date of last counteraction effects. This works fine the first time the forecast is run after a new bg value comes in, but once the counteraction effects cache is up to date, re-running the forecast would mean the the first insulin effect is after the starting bg. We need to have the first insulin effect before starting bg, in order to calculate the delta. If we only have effects starting at the next simulation point after starting bg, then the first forecast point will not include insulin effects, and the forecast can be falsely high, at times creating a fairly extreme jump, like when significant carbs are on board:
The other key part to trigger this "jump" is that momentum has to be disabled for some reason, like mixed provenance …
> Fixes for Insulin effect startdate

- Common/Extensions/OSLog.swift
- Loop.xcodeproj/xcshareddata/xcschemes/WatchApp.xcscheme
- WatchApp Extension/Controllers/ActionHUDController.swift
- WatchApp Extension/Controllers/ChartHUDController.swift
- WatchApp Extension/Extensions/Date.swift
- WatchApp Extension/Extensions/NSUserDefaults+WatchApp.swift
- WatchApp Extension/Scenes/GlucoseChartScene.swift
- WatchApp/Base.lproj/Interface.storyboard
Also includes a drive-by fix for a SDK warning about updating label text too soon
> Support zooming in and out on the Watch app chart by single & double-tapping

- Loop.xcodeproj/xcshareddata/xcschemes/WatchApp.xcscheme
- Loop/Managers/DeviceDataManager.swift
- Loop/Managers/LoopDataManager.swift
- Loop/View Controllers/StatusTableViewController.swift
- Loop/View Models/SettingsViewModel.swift
- Loop/Views/BolusEntryView.swift
- Loop/Views/SettingsView.swift
- LoopUI/Views/LoopCompletionHUDView.swift
Support for Manual Temp Basals
> Manual Temp Basal support

- WatchApp Extension/View Models/CarbAndBolusFlowViewModel.swift
Should fix https://github.com/LoopKit/Loop/issues/1708
> Fix duplicate carb from watch issue 

- Loop/View Models/BolusEntryViewModel.swift
- Loop/Views/BolusEntryView.swift
Fixes https://github.com/LoopKit/Loop/issues/1643
> Duplicate carb entries fix

- Loop/Extensions/ChartSettings+Loop.swift
- Loop/View Models/BolusEntryViewModel.swift
Fixes https://github.com/LoopKit/Loop/issues/1712
> Double bolus race fix

- Loop/View Models/BolusEntryViewModel.swift
This change captures bolus amount, pending carb and manual glucose entries before all the asynchronous events of authorization, carb saving, glucose entry saving, and bolus enactment happen, and uses them instead of member variables on `BolusEntryViewModel` that could be updated in response to other asynchronous events in Loop from the UI, or from data stores.
Attempts to fix the issue described here: https://github.com/LoopKit/Loop/issues/1727
> More prevention of race conditions in bolus UI

- Loop/Extensions/SettingsStore+SimulatedCoreData.swift
- Loop/Managers/Alerts/AlertManager.swift
- Loop/Managers/Alerts/UserNotificationAlertIssuer.swift
- Loop/Managers/AnalyticsServicesManager.swift
- Loop/Managers/DeviceDataManager.swift
- Loop/Managers/LoopAppManager.swift
- Loop/Managers/LoopDataManager.swift
- Loop/Managers/SettingsManager.swift
- Loop/Managers/TrustedTimeChecker.swift
- LoopTests/Managers/Alerts/AlertManagerTests.swift
- WatchApp Extension/Views/Carb Entry & Bolus/BolusInput.swift
- WatchApp Extension/Views/Carb Entry & Bolus/Models/BolusPickerValues.swift
* Watch bolus increments standardized when using visual +/- buttons
* Tracking more notification settings.
* Provide TimeInterval to devices for system time offset detected
* Detect system time offset recovery more reliably
> Tidepool merge

- Loop.xcodeproj/project.pbxproj
- Loop/Managers/ServicesManager.swift
- LoopCore/PersistedProperty.swift
- WatchApp Extension/Managers/LoopDataManager.swift
> Persist settings on watch

- Loop/Views/BolusProgressTableViewCell.xib
- "Tap to Stop" wasn't bound to variable
> add missing binding to label

- Loop/Managers/DeviceDataManager.swift
- Loop/Managers/LoopDataManager.swift
- Loop/View Models/BolusEntryViewModel.swift
- Loop/Views/BolusEntryView.swift
- LoopTests/Managers/LoopDataManagerTests.swift
- LoopTests/ViewModels/BolusEntryViewModelTests.swift
Round input bolus before sending to PumpManager, and alert user about too small boluses.
Fixes https://github.com/LoopKit/Loop/issues/1843
> Bolus Input validation

- Loop/Managers/RemoteDataServicesManager.swift
This is a more robust attempt at fixing https://github.com/LoopKit/Loop/issues/1385
Replaces https://github.com/LoopKit/Loop/pull/1812
> Track upload errors for pending retries

- Loop/Managers/DeviceDataManager.swift
In an effort to better track remote bolus/carb failures, this will add additional logging. Also, I there were a few places that the `info` log type was used which apparently wasn't making its way to remote logging services -- switching to `error` type where appropriate.
> Improve remote notification logging

- Loop/Managers/Alerts/AlertManager.swift
Fixes issue reported here: https://loop.zulipchat.com/#narrow/stream/144182-development/topic/.E2.80.9Cloop.20has.20not.20completed.20successfully.20in.200.20minutes.E2.80.9D
> Display correct interval for loop not looping alert

- Loop.xcodeproj/project.pbxproj
Fixes https://github.com/LoopKit/Loop/issues/1597
> Build derived assets earlier for WatchApp Extension

- Loop/Models/LoopConstants.swift
- Loop/View Controllers/CarbEntryViewController.swift
- WatchApp/DerivedAssets.xcassets/Contents.json
One of two PR (see also LoopKit) in response to Feature Request #1862
> Add warning if carb quantity exceeds warning limit

- Loop/Managers/AnalyticsServicesManager.swift
- Loop/Managers/DeviceDataManager.swift
- Loop/Managers/LoopAppManager.swift
- Loop/View Controllers/CarbEntryViewController.swift
- Loop/View Controllers/StatusTableViewController.swift
- Loop/Views/SettingsView.swift
- LoopTests/Managers/SupportManagerTests.swift
Support plugins can now provide `AnalyticsService` features to Loop
> LoopKit Analytics

- Loop.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- WatchApp Extension/ComplicationController.swift
- WatchApp Extension/Extensions/CLKComplicationTemplate.swift
- WatchApp Extension/Info.plist
adding missing code for the X-Large watch complication
> Add X-Large watch complication

- Loop Status Extension/StatusViewController.swift
- Loop/Extensions/DeviceDataManager+BolusEntryViewModelDelegate.swift
- Loop/Managers/DeviceDataManager.swift
- Loop/Managers/ExtensionDataManager.swift
- Loop/Managers/OnboardingManager.swift
- Loop/Managers/Store Protocols/CarbStoreProtocol.swift
- Loop/Managers/Store Protocols/DoseStoreProtocol.swift
- Loop/Managers/Store Protocols/GlucoseStoreProtocol.swift
- Loop/Managers/WatchDataManager.swift
- StatusWidget/StatusWidget.swift
- WatchApp Extension/Managers/LoopDataManager.swift
https://github.com/LoopKit/LoopKit/pull/484
> Updates for HealthKit decoupling changes in LoopKit

- Loop/View Controllers/StatusTableViewController.swift
> restore workout icon active status

- Loop/Managers/LoopDataManager.swift
Issue described in zulip [here](https://loop.zulipchat.com/#narrow/stream/144182-development/topic/IRC.2FGBPAF.20issue.3F)
> Fix predicted BG graph only showing sometimes

- Loop/View Models/CarbEntryViewModel.swift
use LoopConstants instead of hard-coded time intervals for minimum and maximum dates
> use LoopConstants in CarbEntryViewModel.swift

- WatchApp Extension/View Models/CarbAndBolusFlowViewModel.swift
> #2218 add emoji to foodType on watch
