LoopKit/Loop

Loop/Managers/DeviceDataManager.swift, Loop/Managers/LoopDataManager.swift, Loop/Managers/NotificationManager.swift, Loop/View Controllers/StatusTableViewController.swift
=> Comments and refactoring

Loop/Managers/DeviceDataManager.swift, Loop/View Controllers/SettingsTableViewController.swift
... based on whether there is a G5 transmitter configured.
This means @channemann doesn't have to modify code any longer.
This is key to #10
=> Automatically enable/disable the timer tick

README.md
Path for `RemoteSettings-template.plist` was specifying a directory in which the user was already located
=> Fix template filepath

Loop/Info.plist, Loop/View Controllers/StatusTableViewController.swift
Fixes https://github.com/loudnate/Loop/issues/20
=> Open appropriate Dexcom app

Loop/Extensions/NSUserDefaults.swift, Loop/Info.plist, LoopTests/Info.plist, WatchApp Extension/Info.plist, WatchApp/Info.plist
Fixes an issue where the new Nightscout upload preference wasn't saved across app launches
=> Version 0.4.1

Loop.xcodeproj/project.pbxproj, Loop/Base.lproj/Main.storyboard, Loop/Extensions/NibLoadable.swift, Loop/Extensions/UIColor.swift, Loop/Managers/RemoteDataManager.swift, Loop/Models/ServiceAuthentication.swift, Loop/Models/ServiceCredential.swift, Loop/Models/ShareService.swift, Loop/RemoteSettings-template.plist, Loop/View Controllers/AuthenticationViewController.swift, Loop/View Controllers/SettingsTableViewController.swift, Loop/Views/AuthenticationTableViewCell.swift, Loop/Views/AuthenticationTableViewCell.xib, Loop/Views/ButtonTableViewCell.swift, Loop/Views/ButtonTableViewCell.xib, Loop/Views/ValidatingIndicatorView.swift
=> Allow dex credentials to be updated within the app settings

Loop.xcodeproj/project.pbxproj, Loop/AppDelegate.swift, Loop/Managers/AnalyticsManager.swift, Loop/Managers/DeviceDataManager.swift, Loop/Managers/KeychainManager+Loop.swift, Loop/Managers/KeychainManager.swift, Loop/Managers/LoopDataManager.swift, Loop/Managers/RemoteDataManager.swift, Loop/Managers/WatchDataManager.swift, Loop/Models/AmplitudeService.swift, Loop/Models/NightscoutService.swift, Loop/Models/ServiceCredential.swift, Loop/Models/ShareService.swift, Loop/View Controllers/AuthenticationViewController.swift, Loop/View Controllers/BolusViewController.swift, Loop/View Controllers/SettingsTableViewController.swift, Loop/View Controllers/StatusTableViewController.swift
=> Allow NIghtscout credentials to be updated within the app settings

Loop/Managers/DeviceDataManager.swift, Loop/Managers/RemoteDataManager.swift
* Removing some unnecessary state
* Preventing a pre-bolus status read from triggering the loop and history dump
=> Adjustments to pump status uploading:

Loop/View Controllers/SettingsTableViewController.swift
No issues with this in the past two weeks for me, nor in the past week for @channemann.
=> Remove "beta" label from G4 Share Receiver

Loop/Managers/WatchDataManager.swift, WatchApp Extension/Controllers/BolusInterfaceController.swift, WatchApp Extension/Controllers/StatusInterfaceController.swift, WatchApp Extension/Models/BolusSuggestionUserInfo.swift, WatchApp Extension/Models/WatchContext.swift
And honor max bolus on the watch
Progress toward #30
=> Provide bolus amount suggestions for all watch boluses

Loop/Managers/DeviceDataManager.swift
TempBasal and TempBasalDuration must appear in the same order as in the pump
=> Fix order of pump events delivered to NightscoutUploadKit

Loop/Views/GlucoseHUDView.swift
This should work for mg/dl and mmol/L as there is only ever 3 significant digits at most, sometimes 2 when glucose is <=99mg/dl or <=5.5mmol/L
Tested and fixes https://github.com/loudnate/Loop/issues/159
=> Fix for display of glucose

Loop/Base.lproj/Main.storyboard, Loop/Managers/DeviceDataManager.swift, Loop/Models/Glucose.swift, Loop/Models/GlucoseG4.swift, Loop/Models/MySentryPumpStatusMessageBody.swift, Loop/Models/SensorDisplayable.swift, Loop/Models/ShareGlucose+GlucoseKit.swift, Loop/View Controllers/PredictionTableViewController.swift, Loop/View Controllers/StatusTableViewController.swift, Loop/Views/GlucoseHUDView.swift
=> Display sensor state as a binary warning on the glucose HUD

Loop/AppDelegate.swift, Loop/Managers/DeviceDataManager.swift, Loop/View Controllers/SettingsTableViewController.swift, Loop/View Controllers/StatusTableViewController.swift
=> Fixing the removal of Pump and G5 Transmitter ID

Loop/Base.lproj/Main.storyboard, Loop/Managers/StatusChartManager.swift, Loop/View Controllers/SettingsTableViewController.swift, Loop/View Controllers/StatusTableViewController.swift, Loop/Views/SwitchTableViewCell.swift
Fixes #130
Better use of space on iPhone SE and iPhone 7 Plus
=> Better fix for #159

WatchApp Extension/Controllers/AddCarbsInterfaceController.swift, WatchApp Extension/Controllers/BolusInterfaceController.swift, WatchApp Extension/ExtensionDelegate.swift, WatchApp/Base.lproj/Interface.storyboard
=> Using the crown sequencer directly for carb/bolus input

Loop/Managers/LoopDataManager.swift, Loop/Managers/NightscoutDataManager.swift, Loop/Managers/WatchDataManager.swift, Loop/View Controllers/PredictionTableViewController.swift, Loop/View Controllers/StatusTableViewController.swift
For https://github.com/mddub/urchin-cgm/pull/50.
I would appreciate it if someone else (@ps2?) could test this before I merge. You should see something like this in `/api/v1/devicestatus.json?find[loop][$exists]=1`:
```
{
"loop": {
"cob": {
"timestamp": "2016-10-20T23:40:00Z",
"cob": 18.2929316872428
}, ...
}, ...
}
=> Upload carbs-on-board to Nightscout

Loop/View Controllers/StatusTableViewController.swift
Fixes #233
Multiple updates have the potential to interleave, due to being managed by dispatch_groups. Therefore two updates first read the state of the temp basal (e.g. both read nil), then when their async completion runs, the first one sets the temp basal to non-nil and the UITableView is fine, but then the  second one also sets it to non-nil and attempts to insert an extra row in the table view.
=> fix for after-bolus crash

Loop/Base.lproj/Main.storyboard, Loop/View Controllers/BolusViewController.swift
=> Clicking Recommended copies values down! Closes #286

Loop Status Extension/HKUnit.swift, Loop Status Extension/StatusExtensionContext.swift, Loop Status Extension/StatusViewController.swift, Loop/Managers/StatusExtensionDataManager.swift, Loop/View Controllers/StatusTableViewController.swift, Loop/Views/GlucoseHUDView.swift
Pass the raw HKUnit.unitString (eg. mmol<180.1558800000541>/L) through
the context, as opposed to the unitDisplayString which is uses the
glucose-centric version (eg. mmol/L). This way we can properly hydrate
the unit on the extension side and represent it in the extension.
Fixes #311.
=> Properly support mmol/L in the status extension.

Loop Status Extension/StatusViewController.swift, Loop/Extensions/NSBundle.swift, Loop/Info.plist
Register the "Loop" app url scheme in order to make the app an addressable target.
=> Resolve #319: tapping the widget opens the app

Loop/Extensions/NSBundle.swift
The merge of 73b7302 and 82dc3da resulted in an accidental deletion of
mainAppBundleIdentifier from the NSBundle extension.
=> Fix broken build.

Loop/Managers/StatusExtensionDataManager.swift
This change fixes the lock screen widget battery level to work with MiniMed x22 pumps, which do not send MySentry packets.  I believe that this covers issue #325.  The change just makes use of the work done for issue #141 - thanks to the team for that great work!  (Note that I have not been able to test this for regression against x23 model pumps as I do not have one.)
=> Fix widget battery level for x22 pumps

LoopUI/Views/BasalStateView.swift, LoopUI/Views/LevelMaskView.swift, LoopUI/Views/LoopStateView.swift
default value so the animation is deceptive.
This resolves #321.
=> Disable animation on first render, since we'd be animating from a

Loop/Extensions/NSUserDefaults.swift, Loop/Managers/DeviceDataManager.swift, Loop/View Controllers/SettingsTableViewController.swift
Separate CGM sources out into their own section and enforce zero or one
active sources at any given time. This requires a new boolean value to
track whether the G5 transmitter is enabled independently of the actual
transmitter ID.
While we're at it, create a separate config section for the pump to
group it with the pump battery type since those are not really
configuration values and go together.
=> Only allow one active glucose data source

Loop/Managers/DiagnosticLogger+LoopKit.swift, Loop/Managers/LoopDataManager.swift
This PR is a attempt to address https://github.com/LoopKit/Loop/issues/370. The `recommendBolus` function calculates a bolus based on both a glucose prediction with momentum, and one without, and returns the smaller bolus of the two.
Note that currently the retrospective effect is not used in the bolus calculation without momentum. We will test over the next few days. Any comments welcome.
=> remove +ve momentum from bolus calculation

Common/Extensions/NumberFormatter.swift, Loop.xcodeproj/project.pbxproj, Loop/Extensions/ChartPoint.swift, Loop/Extensions/NightscoutUploader.swift, Loop/Info.plist, Loop/Managers/DeviceDataManager.swift, Loop/Managers/DiagnosticLogger+LoopKit.swift, Loop/Managers/LoopDataManager.swift, Loop/Managers/NightscoutDataManager.swift, Loop/Managers/RemoteDataManager.swift, Loop/Managers/StatusChartManager+LoopKit.swift, Loop/Managers/StatusChartManager.swift, Loop/Managers/WatchDataManager.swift, Loop/Models/Glucose.swift, Loop/Models/ServiceAuthentication/AmplitudeService.swift, Loop/View Controllers/BolusViewController.swift, Loop/View Controllers/GlucoseThresholdTableViewController.swift, Loop/View Controllers/PredictionTableViewController.swift, Loop/View Controllers/SettingsTableViewController.swift, Loop/View Controllers/StatusTableViewController.swift
- Refactoring charting code to remove unnecessary work and unnecessary caching
- userDefaults["ModifiedCarbEntries"] never cleared for non-nightscout users
- Fixing a black screen during launch animation
- Disabled Amplitude's attempted CLLocation usage
=> Charts refactor

Loop Status Extension/StatusViewController.swift
regardless of the units used in the StatusExtensionContext.
This resolves #433
=> Widget should always display data using the preferred dispay unit,

Loop Status Extension/Base.lproj/MainInterface.storyboard
"<NSLayoutConstraint:0x600000097430 LoopUI.ChartContentView:0x7f808c50aae0.height >= 100   (active)>",
"<NSLayoutConstraint:0x60000009c2f0 'UISV-hiding' LoopUI.ChartContentView:0x7f808c50aae0.height == 0   (active)>"
Lower the priority of the height >= 100 constraint.
=> Break the tie between two visual constraints.

Loop/Managers/LoopDataManager.swift
This reverts behavior that added in #370.  That change caused confusion, because the forecast that drove bolusing was different from the forecast shown.  #435 is one example.
For those people that feel that Loop is being too aggressive in times of unexpected upward bg change, they should look into retrospective correction, and see what their forecast looks like with and without it enabled.  That may be a feature that you want to turn off.
=> Use standard forecast for bolus recommendations.

Common/Extensions/NSTimeInterval.swift, Common/Extensions/NumberFormatter.swift, Loop.xcodeproj/project.pbxproj, Loop/AppDelegate.swift, Loop/Extensions/NSUserDefaults.swift, Loop/Managers/LoopDataManager.swift, Loop/Managers/NightscoutDataManager.swift, Loop/Managers/StatusExtensionDataManager.swift, Loop/Managers/WatchDataManager.swift, Loop/View Controllers/ChartsTableViewController.swift, Loop/View Controllers/PredictionTableViewController.swift, Loop/View Controllers/StatusTableViewController.swift, LoopUI/Managers/StatusChartsManager.swift, LoopUI/Models/ChartAxisValueDoubleUnit.swift
- Refactors common behavior between chart view controllers into a superclass
- Renames "dataManager" to "deviceManager" in a few places
- Improves touch tracking in charts
- Fixes an issue where the Y-axis line was visible
- Reduces excess padding on the right side of charts
=> Rethink the API for clients to read loop status; other cleanup.

Common/Models/StatusExtensionContext.swift, Loop Status Extension/StatusViewController.swift, Loop.xcodeproj/project.pbxproj, Loop/Managers/DeviceDataManager.swift, Loop/Managers/LoopDataManager.swift, Loop/Managers/StatusExtensionDataManager.swift, Loop/Models/NetBasal.swift, Loop/Models/StatusExtensionContext+LoopKit.swift, Loop/View Controllers/StatusTableViewController.swift
=> Restore last temp basal value from status extension context on launch

Loop/Managers/DeviceDataManager.swift
=> Fixing an issue where idle timer wasn't asserted as running unless pump data was stale

.gitignore, Loop.xcodeproj/project.pbxproj
to make framework development more integrated
=> Adding support for setting up a workspace

Loop.xcodeproj/project.pbxproj, Loop/Extensions/DoseStore.swift, Loop/Managers/DeviceDataManager.swift
And install homebrew/carthage if needed.
=> Treat period after rewind as suspend

Common/Extensions/HKUnit.swift, Loop.xcodeproj/project.pbxproj, Loop/Base.lproj/Main.storyboard, Loop/Extensions/NSUserDefaults.swift, Loop/Managers/AnalyticsManager.swift, Loop/Managers/LoopDataManager.swift, Loop/Managers/RemoteDataManager.swift, Loop/Managers/StatusChartsManager+LoopKit.swift, Loop/Models/Insulin/ExponentialInsulinModelPreset.swift, Loop/Models/Insulin/InsulinModelSettings.swift, Loop/Models/Insulin/WalshInsulinModel.swift, Loop/View Controllers/InsulinModelSettingsViewController.swift, Loop/View Controllers/PredictionTableViewController.swift, Loop/View Controllers/RadioSelectionTableViewController.swift, Loop/View Controllers/SettingsTableViewController.swift, Loop/View Controllers/StatusTableViewController.swift, Loop/View Controllers/TextFieldTableViewController.swift, Loop/Views/TitleSubtitleTextFieldTableViewCell.swift, LoopUI/Managers/StatusChartsManager.swift, LoopUI/Models/ChartLineModel.swift
Uses the new [exponential insulin model](https://github.com/LoopKit/Loop/issues/388#issuecomment-317938473) available in [LoopKit](https://github.com/LoopKit/LoopKit/blob/v1.4.3/InsulinKit/ExponentialInsulinModel.swift)
=> Allow selection of new insulin curves

Loop/Managers/CGM/DexCGMManager.swift, Loop/Managers/DeviceDataManager.swift
- No longer disable Share backfill after the first reading
- Don't fetch from Share unless G4/G5 data is old
- Report bad G5 calibration state as a CGM error so it surfaces to users
=> Dexcom share more agressive fetch

Loop/View Controllers/CarbAbsorptionViewController.swift, Loop/View Controllers/StatusTableViewController.swift
=> fix intermittent crash on deleting carbs

Loop/Extensions/NewPumpEvent.swift, Loop/Managers/DeviceDataManager.swift
Set pending bolus end date. 
Also, save pump timezone to UserDefaults if not set.
=> Set pending bolus end date

Loop/Managers/DeviceDataManager.swift
If pump data fetch fails, subsequent timer events will now trigger another attempt.
This should help with general stability and can fix extreme cases where MySentry packets are arriving just after CGM updates, and routinely blocking pump data reads.
=> Fetch pump data if needed, even after .noData CGM updates.

Loop/Managers/CGM/DexCGMManager.swift, Loop/Managers/DeviceDataManager.swift
=> Fix sensor state display

Loop/View Controllers/TextFieldTableViewController.swift
Reminder to check pump's max basal rate when setting the Loop's max basal rate
=> Add prompt on Max Basal Rate

Loop/Managers/LoopDataManager.swift, Loop/Managers/NightscoutDataManager.swift, Loop/Managers/WatchDataManager.swift, Loop/View Controllers/BolusViewController+LoopDataManager.swift
Essentially handle Bolus recommendation the same as Basal recommendations.  There is probably historic reasons why these are treated differently.  Given that update() is always called before recommendBolus it does not make a lot of functional sense though.
This is in preparation of being able to automatically do bolus' out of LoopDataManager.
=> Refactor Bolus recommendation code

Loop/Managers/LoopDataManager.swift
This technically isn't necessary as they are updated in the same
function but for consistency and not to forget during the next
refactoring this is protecting the user from getting a potentially
dangerous out of date recommendation.
=> Reset recommendedBolus if we have a new prediction.

WatchApp Extension/Controllers/BolusInterfaceController.swift
previously was using 75% of the pickerValue
also remove the extra casting
=> select the pickerValue based on 75% of recommendedBolus

Common/Extensions/Double.swift, Loop/Managers/DeviceDataManager.swift, Loop/Managers/WatchDataManager.swift, WatchApp Extension/Base.lproj/Localizable.strings, WatchApp Extension/Controllers/ActionHUDController.swift, WatchApp Extension/Controllers/AddCarbsInterfaceController.swift, WatchApp Extension/Controllers/BolusInterfaceController.swift, WatchApp Extension/Controllers/ChartHUDController.swift, WatchApp Extension/Controllers/HUDInterfaceController.swift, WatchApp Extension/Extensions/WCSession.swift, WatchApp Extension/Managers/LoopDataManager.swift, WatchApp Extension/Scenes/GlucoseChartScene.swift, WatchApp/Assets.xcassets/AppIcon.appiconset/Contents.json, WatchApp/Assets.xcassets/Graph menu icons/1-hour-graph.imageset/Contents.json, WatchApp/Assets.xcassets/Graph menu icons/2-hour-graph.imageset/Contents.json, WatchApp/Assets.xcassets/Graph menu icons/3-hour-graph.imageset/Contents.json, WatchApp/Assets.xcassets/bolus.imageset/Contents.json, WatchApp/Assets.xcassets/carbs.imageset/Contents.json, WatchApp/Assets.xcassets/loop/loop_aging.imageset/Contents.json, WatchApp/Assets.xcassets/loop/loop_fresh.imageset/Contents.json, WatchApp/Assets.xcassets/loop/loop_stale.imageset/Contents.json, WatchApp/Assets.xcassets/loop/loop_unknown.imageset/Contents.json, WatchApp/Assets.xcassets/pre-meal.imageset/Contents.json, WatchApp/Assets.xcassets/workout.imageset/Contents.json, WatchApp/Base.lproj/Interface.storyboard
- Update IOB and COB immediately after carb/bolus send
- Adjust complication push budget to spend evenly before midnight
- Adjustments for Series 4, including rounded action buttons, correct text margin insets, and using system scroll haptics
- Improve efficiency of the chart redraw
=> Watch Feature Updates

Loop/Managers/StatusChartsManager+LoopKit.swift
This only affects pump managers that do not report boluses as instantaneous.
=> Display boluses with a duration longer than 5 minutes

README.md
Per https://gitter.im/LoopKit/Loop "we have moved discussions to a new place, please post in zulipchat now". This PR updates the README badge accordingly, as suggested in https://zulipchat.com/help/join-zulip-chat-badge
=> Update chat badge

WatchApp Extension/Controllers/AddCarbsInterfaceController.swift
Small change to present the bolus controller after a carb entry on the watch only in cases where the bolus recommendation is non-zero.   Always presenting the bolus interface even for zero recommended bolus could be considered as a form of carb entry confirmation, but it doesn't seem necessary with the success haptic now in place, and also doesn't seem consistent with the behavior in the phone app and the overall "assume success but alert on failure" approach of the rest of the UI.
=> Only present non-zero bolus suggestion on watch after carb entry

Cartfile.resolved, Common/Extensions/GlucoseRangeSchedule.swift, Loop/Managers/DoseMath.swift, LoopUI/Extensions/ChartPoint.swift, LoopUI/Managers/StatusChartsManager.swift, WatchApp Extension/Models/GlucoseChartData.swift, WatchApp Extension/Scenes/GlucoseChartScene.swift, WatchApp Extension/Scenes/GlucoseChartValueHashable.swift
This fixes a bug where users whose graphs are broken when their target range unit doesn't match the HealthKit preferred unit
=> Fix target range charting unit mismatch

Loop/Managers/NightscoutDataManager.swift
depends on https://github.com/ps2/rileylink_ios/pull/522
this will let us display 50+ U on the pump pill in Nightscout
uploaded device status looks like this:
```
"pump": {
"bolusing": false,
"suspended": false,
"secondsFromGMT": -25200,
"model": "Eros",
"pumpID": "1F01ACAB",
"clock": "2019-05-04T19:19:35Z",
"manufacturer": "Insulet"
}
```
```
"pump": {
"suspended": false,
"pumpID": "999999",
"manufacturer": "Medtronic",
"model": "522",
"battery": {
"percent": 100
},
"reservoir": 90.6,
"bolusing": false,
"clock": "2019-05-04T05:13:58Z",
"secondsFromGMT": -25200
}
```
=> include pump manufacturer and model in the pump status

LoopUI/Charts/ChartsManager.swift
Updated version of #919. Thanks @reelman!
=> Show 12h or 24h time on chart x-axis depending on locale

Loop/Base.lproj/Localizable.strings, Loop/Models/ServiceAuthentication/NightscoutService.swift, Loop/de.lproj/Localizable.strings, Loop/es.lproj/Localizable.strings, Loop/fr.lproj/Localizable.strings, Loop/it.lproj/Localizable.strings, Loop/nb.lproj/Localizable.strings, Loop/nl.lproj/Localizable.strings, Loop/pl.lproj/Localizable.strings, Loop/ru.lproj/Localizable.strings, Loop/zh-Hans.lproj/Localizable.strings, LoopTests/KeychainManagerTests.swift
Little tweak: the Nightscout project recommends using Heroku and NOT using Azure to host the project.
=> update Nightscout URL placeholder to Heroku

LoopUI/Charts/PredictedGlucoseChart.swift
Fixes overrides being drawn incorrectly (wrong units) when schedule has different units than currently being displayed.
=> Fix display of correction range override

Scripts/copy-frameworks.sh
This fixes the check for duplicate versions of Carthage and workspace built frameworks existing, and follows symlinks to avoid installing frameworks as symlinks in an archive build.
=> Update copy-frameworks for TestFlight

Loop/Models/ServiceAuthentication/NightscoutService.swift
since remote-overrides are coming, this might be an easy safety hide.
=> hide the saved API secret by default in NS services display

Loop/Managers/DeviceDataManager.swift
Fix issue with PumpManager ble update coming in right after cgm update arrives, causing two loops to be run in rapid succession.
=> Multiple cycles triggered in short window.

Loop.xcodeproj/project.pbxproj, Scripts/capture-build-details.sh
SRCROOT environment variable is not escaped, when using it as part of a path it should be escaped or enclosed in quotes
Tested on Workspace build
=> Fixed building from directories containing spaces

Loop/AppDelegate.swift, Loop/Base.lproj/Main.storyboard
Pause launch if launching before first unlock. Workaround for #1170
=> Settings loss patch

Loop/Managers/LoopDataManager.swift
Investigations into delayed display and dosing availability have shown significant cache misses in CarbStore, which results in a HealthKit query.  When the phone has been locked for a significant amount of time, HealthKit queries can perform very slowly, as HealthKit is processing journaled data and doing other housekeeping. This fix increases the cache length to a longer value that should eliminate most cache misses.
=> Set carb cache length to 24 hours.

Loop/Managers/LoopDataManager.swift
Suspend threshold evaluation (when basal should be cut off), and dosing threshold (when any dosing above basal should be prevented), were not including current bg in the evaluation. This moves the window of consideration (DIA duration) back to the point of the most recent bg, rather than the current time.
=> Include current bg for suspend threshold and dosing thresholds

DoseMathTests/DoseMathTests.swift, Loop/Managers/DoseMath.swift, LoopCore/Insulin/ExponentialInsulinModelPreset.swift
Adds delay to the insulin model presets, reverts hard coded delay and subtraction of delay in DoseMath. This is a companion PR to LoopKit PR https://github.com/LoopKit/LoopKit/pull/315. Upon review, and any further updates, the two PR's should be merged concurrently. This Loop PR and the LoopKit PR 315 serve the same main purpose of fixing the dose math as https://github.com/LoopKit/Loop/pull/1238, which should be closed once these two PR's are merged.
=> Insulin model delay

DoseMathTests/DoseMathTests.swift, Loop/Managers/DoseMath.swift
A 10-min delay is included in calculation of effected insulin so that the insulin model used in dose calculations becomes consistent with the insulin model used for prediction calculations. 
This addresses an issue brought up in the [Partial Bolus Recommendation](https://loop.zulipchat.com/#narrow/stream/148543-Loop/topic/Partial.20Bolus.20Recommendations) topic on Loop Zulip where a nonzero bolus recommendation is observed immediately after a bolus recommendation has been accepted.  DoseMathTests have been updated accordingly.
=> Include insulin model delay in computation of dose

Loop/Managers/NightscoutDataManager.swift
Issue reported on zulipchat: https://loop.zulipchat.com/#narrow/stream/144182-development/topic/trend.20arrow.20inconsistency
The code for uploading to nightscout has been inside Loop for a very long time, but has up to now only been used by the medtronic enlite cgmmanager. Now that the Dexcom cgmmanager also can upload to loop, more users have started using this feature. 
I've detected that the loop trend arrow doesn't always match the trend arrow displayed in nightscout. This fixes that by uploading the correct trend arrow names, adding those that were lacking from the original implementation. 
(My guess is that Loop's code for uploading glucose trend arrows predates nightscout's support for granular trend arrows. This code should be safe because Nightscout users generally update fast …
=> Fix nightscout uploading trend arrow inconsistency

Common/Models/WatchContext.swift, Loop Status Extension/StatusViewController.swift, Loop.xcodeproj/project.pbxproj, Loop/Managers/LoopDataManager.swift, Loop/Managers/WatchDataManager.swift, Loop/View Controllers/StatusTableViewController.swift, LoopCore/LoopCompletionFreshness.swift, LoopCore/LoopSettings.swift, LoopUI/Views/GlucoseHUDView.swift, LoopUI/Views/LoopCompletionHUDView.swift, WatchApp Extension/ComplicationController.swift, WatchApp Extension/Controllers/HUDInterfaceController.swift, WatchApp Extension/Extensions/CLKComplicationTemplate.swift, WatchApp Extension/Extensions/UIColor.swift, WatchApp Extension/Managers/LoopDataManager.swift
From https://github.com/tidepool-org/Loop/pull/44
=> Denote stale glucose as three dashes

Loop/View Controllers/StatusTableViewController.swift
When tapping on the loop completion HUD view in the case of an error, a 'Retry' button allows the user to manually reattempt a loop.
This behavior is valuable when the reason for loop failure is expected to have been resolved, e.g. the user unsuspends their pump or power cycles their RileyLink in the case of comms failure. The user can now assert that their action did in fact resolve the problem, rather than waiting five minutes.
=> Support enacting manual loop if loop error

Common/sv.lproj/Intents.strings, Common/sv.lproj/Localizable.strings, DoseMathTests/sv.lproj/Localizable.strings, Learn/sv.lproj/Localizable.strings, Learn/sv.lproj/Main.strings, Loop Status Extension/sv.lproj/Localizable.strings, Loop Status Extension/sv.lproj/MainInterface.strings, Loop/sv.lproj/InfoPlist.strings, Loop/sv.lproj/Localizable.strings, Loop/sv.lproj/Main.strings, LoopUI/sv.lproj/Localizable.strings, WatchApp Extension/sv.lproj/Localizable.strings, WatchApp/sv.lproj/Interface.strings
Updated and corrected spellings of all Swedish translations.
=> Chore: Updated Swedish (sv) translations.

Loop/View Controllers/SettingsTableViewController.swift
Currently, Loop doesn't display any message when the user attempts to edit the basal schedule without a configured pump, which can be confusing to new users. This is just a simple UIAlert that displays when the row is tapped without a configured pump; completely open to changing the wording to make it better.
=> Add warning when user attempts to edit basal schedule without a configured pump

Learn/fi.lproj/InfoPlist.strings, Loop.xcodeproj/project.pbxproj, Loop/fi.lproj/InfoPlist.strings, Loop/fi.lproj/Localizable.strings, Loop/fi.lproj/Main.strings, LoopUI/fi.lproj/Localizable.strings, WatchApp Extension/fi.lproj/Localizable.strings, WatchApp/fi.lproj/Interface.strings
Here is a set of Finnish translation updates, including previously missing strings. 
Workflow used to create the translations:
1. In Xcode: Export for Localization.
2. Opened and edited the exported xliff file.
3. If there were any missing target tags in the xliff file, I added & translated.
4. Import Localizations > imported the xliff file.
5. Commit changes & push.
NOTE: I see there are some changes in the project.pbxproj and InfoPlist files too, made by Xcode and I'm not sure if these changes should be included in this PR or not.
=> Finnish translations update

README.md
The Loop icon image at the top of README.md is broken. This change fixes the image path to reference the `DefaultAssets.xcassets` folder instead of `Assets.xcassets`.
=> Fix app icon link in README.md

Loop/Managers/DeviceDataManager.swift, Loop/View Controllers/StatusTableViewController.swift
When Loop is failing to loop and displays a red or yellow loop, the user can tap on the red loop and see the last error, and have an option to Retry. The Retry option was just trying to loop again, without triggering a device data refresh. This changes the retry button to attempt to refresh pump and CGM data, so if any comms issues have been resolved by the user (bringing the RL/phone back in range, etc), but Loop hasn't tried comms with the devices, this will trigger a check, and will let the user resume automatic dosing more quickly.
=> Red loop retry should refresh device data

Loop/View Controllers/CarbEntryViewController.swift
This is a small fix to address the date picker UI change that was made in iOS 14; I added a change to force the picker to show up in the .wheels style that it had before.
=> Fix date picker appearance for carb entry in iOS 14

Loop/View Controllers/CarbEntryViewController.swift, Loop/Views/BolusEntryView.swift
There are a few groupings in Loop right now that don't get read correctly by VoiceOver, so I added the appropriate logic. I also snuck in a fix for the date picker style for the carb entry screen.
=> Improve accessibility when using VoiceOver

Loop/Managers/AnalyticsServicesManager.swift, Loop/Managers/DeviceDataManager.swift, Loop/Managers/LoopDataManager.swift
Fixes an issue where a failing loop (triggered by a CGM timer being woken by pump disconnect) could prevent a subsequent loop (triggered by pump), that could have succeeded, from running.
Also fixes a threading issue in LDM where loop() was leaving releasing dataAccessQueue before the loop was finished, allowing concurrent calls.
=> Loop timing updates

Loop/Managers/DeviceDataManager.swift
This PR, along with [Update capture-build-details.sh](https://github.com/LoopKit/Loop/pull/1591) will assist in providing full pod history for support of both Eros and Dash pods.
This PR:
* Removes some of the verbose portions of the Loop Report that are now available in the Export Critical Event Logs tab
* Extends the duration of the reported log to 84 hours, which should cover the full history of a pod for most cases
* Adds a header marker for the code Version in the markdown output
The last 2 items on the list simplify the work required to parse and report on Dash pods as we are testing the code to support Dash implementation.
The extended duration is helpful for supporting both Eros and Dash when Loop users report problems with their pods online.
Note that without the full history …
=> increase log duration, add markdown header mark

Loop/Managers/DeviceDataManager.swift, Loop/Managers/LoopDataManager.swift, Loop/View Controllers/CarbEntryViewController.swift, Loop/View Controllers/StatusTableViewController.swift, Loop/View Models/BolusEntryViewModel.swift, Loop/Views/BolusEntryView.swift, LoopTests/ViewModels/BolusEntryViewModelTests.swift
There are some reports of the existing clear-on-edit mechanism not actually clearing out the editable bolus amount field in the bolus view. This uses a different strategy to clear the field. 
Looking to test reports from those who have experienced the failure to clear. 
It also contains changes to streamline forecast and recommendation generation; previously, bringing up the view would cause at least 7 forecast predictions to be run, and would cause flashing as the various parts of the UI updated, usually rendering a view without the bolus and then rendering one with the bolus.
=> Bolus clear fix

Loop.xcodeproj/xcshareddata/xcschemes/WatchApp.xcscheme
Per the some discussion on [Zulip](https://loop.zulipchat.com/#narrow/stream/144182-development/topic/WatchApp.20on.20dev/near/269413953), I think the removal of the `WatchApp.xcscheme` in [f54695d](https://github.com/LoopKit/Loop/commit/f54695d9fb82b2b92e1c4e99e1db71b243422c3b#diff-da280ff98f2d6a7e3434963f8d8354127ce29e40b9470a3cf9a15cff05904722) may have been unintentional. In any case, believe it makes sense to restore it, particularly because it allows us to sidestep #1597 and easily launch with the debugger attached.
=> Restore WatchApp.xcscheme removed in f54695d

WatchApp Extension/Extensions/NSUserDefaults+WatchApp.swift
Based on some discussion in zulip [here](https://loop.zulipchat.com/#narrow/stream/144182-development/topic/WatchApp.20on.20dev/near/271923672)
The shorter window has made it easier for me to see the recent trends and near-term projections, which is where the watch is most useful 🙂
=> Reduce WatchApp visible duration from 6 hours to 2 hours

Loop/Managers/NotificationManager.swift
Remote bolus notifications were not formatted properly for values like 1.02, which would round to 1.1 in the visible notifications. (would not affect delivery though). I was only supporting 1 precision unit. The screenshot below is with the fix.
=> Support more precision in remote bolus notifications

Common/FeatureFlags.swift, Loop Status Extension/StatusViewController.swift, Loop/Managers/DeviceDataManager.swift
Per the discussion on [Zulip](https://loop.zulipchat.com/#narrow/stream/144182-development/topic/Reading.20from.20Apple.20Health/near/273676678) and further discussion in an unrelated [issue](https://github.com/LoopKit/LoopKit/issues/407#issuecomment-1120449748), this PR splits `FeatureFlags.observeHealthKitSamplesFromOtherApps` into three flags:
* `observeHealthKitCarbSamplesFromOtherApps`
* `observeHealthKitDoseSamplesFromOtherApps`
* `observeHealthKitGlucoseSamplesFromOtherApps`
Reading carb samples is "opt-in" via `OBSERVE_HEALTH_KIT_CARB_SAMPLES_FROM_OTHER_APPS_ENABLED`, and reading dose and glucose samples are "opt-out" to maintain backward-compatibility with `OBSERVE_HEALTH_KIT_SAMPLES_FROM_OTHER_APPS_DISABLED`. I don't love the intersection of 4 swift compiler directives, but it …
=> Split FeatureFlags.observeHealthKitSamplesFromOtherApps into three flags

Loop/View Controllers/StatusTableViewController.swift
This modification disables the Pre-Meal icon on the app home screen for the case where the Pre-Meal ranges are not set, i.e., equal to [:].
This change, in conjunction with [LoopKit PR #400: add a reset button to Pre-Meal screen](https://github.com/LoopKit/LoopKit/pull/400) should complete the required changes needed to close Issue #1654
=> Make Pre-Meal icon inactive if nil

Loop.xcodeproj/project.pbxproj, Loop/AppDelegate.swift, Loop/Extensions/DiagnosticLog.swift, Loop/Managers/Alerts/AlertManager.swift, Loop/Managers/Alerts/AlertStore.swift, Loop/Managers/Alerts/UserNotificationAlertIssuer.swift, Loop/Managers/AnalyticsServicesManager.swift, Loop/Managers/CGMStalenessMonitor.swift, Loop/Managers/DeviceDataManager.swift, Loop/Managers/DoseEnactor.swift, Loop/Managers/LocalTestingScenariosManager.swift, Loop/Managers/LoopAlertsManager.swift, Loop/Managers/LoopAppManager.swift, Loop/Managers/LoopDataManager.swift, Loop/Managers/SharedLogging.swift, Loop/Managers/SupportManager.swift, Loop/Managers/TestingScenariosManager.swift, Loop/Managers/TrustedTimeChecker.swift, Loop/Managers/WatchDataManager.swift, LoopTests/DiagnosticLogTests.swift
DiagnosticLog is our custom logger that logs messages to both OSLog and forwards logs to any Services that support Logging, like the Loggly service. 
There is an issue defining methods with the StaticString type, that receive strings from other libraries (at least wrt to strings in Console logs). The DiagnosticLog API is located in LoopKit and receives calls from other libraries, like Loop. That sysdiagnose Logs in console will show "<compose failure [UUID]>". DiagnosticLog was disabled several weeks ago in favor of using OSLog directly to fix this; however, that removed our logging to Services, like Loggly.
The fix in this PR is to move the DiagnosticLog from LoopKit to Loop to keep the StaticStrings in the same module. This limits DiagnosticLog to only supporting logs in the Loop module …
=> Fix DiagnosticLog missing logs in Console

Loop/Managers/DeviceDataManager.swift, Loop/Managers/RemoteDataServicesManager.swift
This is a potential fix for https://github.com/LoopKit/Loop/issues/1642. In the master branch we were only uploading Glucose data when `CGMManager.shouldSyncToRemoteService` returned true. That feature was lost in dev with subsequent refactors.
This change will respect that value but checking just before a glucose upload is performed. I'm not that familiar with the history of this setting so I may be missing the bigger picture to how this is intended to work.
=> Avoid uploading glucose data to Remote Services when disabled

Loop/Managers/DeviceDataManager.swift, Loop/Managers/LoopDataManager.swift, Loop/Managers/SettingsManager.swift, Loop/Managers/Store Protocols/LatestStoredSettingsProvider.swift, LoopTests/Managers/LoopDataManagerTests.swift, LoopTests/Mock Stores/MockSettingsStore.swift
Storing migrated settings was failing as the store call was happening before device token had been fetched, and we guard against that on real devices. This change allows SettingsManager to keep the main copy of settings, so the migration can happen, followed by device token fetch, followed by actual storage into SettingsStore
=> Handle settings migration with delayed device token fetch

LoopUI/Charts/PredictedGlucoseChart.swift, LoopUI/Extensions/ChartPoint.swift
This is an updated attempt at solving the issue described here: https://github.com/LoopKit/Loop/issues/1644
The volleyball target shows an override that is only adjusting insulin, and not target.
=> Highlight area where override is active

Loop.xcodeproj/project.pbxproj, Loop/Managers/DeviceDataManager.swift, Loop/Models/RemoteCommand.swift, LoopTests/Models/RemoteCommandTests.swift
The Careportal includes an Event Time field when entering remote carbs. That date is not included in the Push Notification. That has led to some confusion and also a feature request to support remote carb entries in the future or past. 
I have a separate PR for Nightscout to begin including that date ([7512](https://github.com/nightscout/cgm-remote-monitor/pull/7512)) I don't think this Loop PR needs to wait for that one to merge though.
This Loop PR will parse the "created-date" from the push notification when it is included (when a user has the code in PR 7512).
=> Allow Remote Carb Entries in Past or Future

Loop.xcodeproj/project.pbxproj, Loop/Extensions/UserDefaults+Loop.swift, Loop/Managers/Alerts/AlertManager.swift, Loop/Managers/DeviceDataManager.swift, Loop/Managers/LoopAppManager.swift, Loop/Managers/LoopDataManager.swift, Loop/Models/CrashRecoveryManager.swift, Loop/View Controllers/StatusTableViewController.swift
Add CrashRecoveryManager, which generates an alert, and prevents looping, if a crash during dosing enactment or storage is encountered. 
Mitigation for #1796 
Also fixes "black screen" issue when alerts are issued before status view controller is presented, by deferring alert issuance.
=> Crash Recovery Manager

StatusWidget/GlucoseView.swift, StatusWidget/LoopCircleView.swift, StatusWidget/SmallStatusWidgetEntryView.swift, StatusWidget/StatusWidget.swift
Glucose data for the widget is fetched from CoreData, not from the context (UserDefaults).  In the case where Loop has not updated the context, but there is fresh data in GlucoseStore, the glucose staleness should be based off of how recently we fetched data from GlucoseStore.
=> Widget glucose staleness

LoopUI/Charts/PredictedGlucoseChart.swift
Updated version of https://github.com/LoopKit/Loop/pull/1757, to fix https://github.com/LoopKit/Loop/issues/1741
=> Fix target range display when override and premeal are both active

Loop/Managers/DeviceDataManager.swift, Loop/Models/LoopConstants.swift, Loop/Models/RemoteCommand.swift, Loop/View Controllers/CarbEntryViewController.swift, LoopTests/Models/RemoteCommandTests.swift
A few changes in this PR:
* Enforce carb absorption range of 30 minutes to 8 hours.
* Use the user's default medium absorption if none supplied (A previous TODO in code).
* Add tests.
This issue was reported in https://github.com/LoopKit/Loop/issues/1841
Sending very large values also seems to make Loop crash or at least cause all carbs to disappear as I seemed to reproduce and also reported by a Loop user recently https://loop.zulipchat.com/#narrow/stream/144182-development/topic/Red.20loop.
=> Handle invalid remote carb absorption values

Loop/Extensions/DeviceDataManager+BolusEntryViewModelDelegate.swift, Loop/Managers/DeviceDataManager.swift, Loop/Managers/LoopDataManager.swift, Loop/Managers/WatchDataManager.swift, Loop/View Controllers/CarbEntryViewController.swift, Loop/View Controllers/StatusTableViewController.swift, Loop/View Models/BolusEntryViewModel.swift, Loop/Views/BolusEntryView.swift
Fixes https://github.com/LoopKit/Loop/issues/1858
Simplifies error prone callback spaghetti of saving glucose/carbs/bolusing by switching to async context, which makes it easier to ensure that the remote dosing decision is updated at the right time.
=> Trigger dosing decision creation after manual bolus or carb editing

Loop.xcodeproj/project.pbxproj, Loop/View Controllers/CarbEntryViewController.swift, Loop/View Controllers/StatusTableViewController.swift, Loop/View Models/BolusEntryViewModel.swift, Loop/Views/BolusEntryView.swift, Loop/Views/ManualGlucoseEntryRow.swift, LoopTests/ViewModels/BolusEntryViewModelTests.swift
Updates BolusViewEntryModelTests to avoid complicated, error prone, waits on main.
Extracted glucose entry row into separate view.
Require iOS 15.
=> Bolus view tests

Loop/Managers/DeviceDataManager.swift, Loop/Managers/NotificationManager.swift, Loop/Managers/RemoteDataServicesManager.swift
We have had some reports of failed remote deliveries and the current error messaging isn't very helpful for understanding why a remote push failed. This information is captured in diagnostic logs but ideally this would be surfaced to a user. This PR enhances our user-facing errors messages.
Associated PRs:
LoopKit: https://github.com/LoopKit/Loop/pull/1867
NightscoutService: https://github.com/ps2/NightscoutService/pull/24
=> Improve Remote failure error messaging

Loop/Managers/DeviceDataManager.swift, Loop/Managers/RemoteDataServicesManager.swift
Nightscout remote treatments (bolus, carbs, overrides) are sometimes delayed in showing up in Nightscout. This seems related to the app being in the background.
The primary reason for the delays seems to be the various delivery/upload threads halting their progress while in the background -- iOS just stops giving CPU time. Opening the app will "wake" the threads back up and finish the upload process.
A mechanism for synchronously waiting on the GCD groupTask did not seem to working as intended from what could tell. It seems the reason was there was no groupTasks to wait on when the `wait` was invoked as the code that enacts treatments is highly asynchronous. There were often several dispatches to different queues to wait on before the groupTasks were added.
The change in this PR is to use …
=> Ensure remote treatments are uploaded to NS while in background

Common/FeatureFlags.swift, WatchApp Extension/Controllers/HUDInterfaceController.swift, WatchApp/Base.lproj/Interface.storyboard
Restores the eventual blood glucose label in the WatchApp user interface and shows/updates it on the basis of a new feature flag `showEventualBloodGlucoseOnWatchEnabled` governed by the `SHOW_EVENTUAL_BLOOD_GLUCOSE_ON_WATCH_ENABLED` compiler directive.
This is functionally identical to the code that exists in the master branch, but it's wrapped in a feature check and one additional let to ensure that the eventualGlucoseValue can be obtained.
Let me know if any further changes are needed.
=> Restore support for showing eventual blood glucose on watch

Common/FeatureFlags.swift
Reverse the logic so that eventual glucose is shown on the watch by default.
New feature flag is SHOW_EVENTUAL_BLOOD_GLUCOSE_ON_WATCH_DISABLED
* test with no flag, eventual glucose shows on watch
* test with flag: SHOW_EVENTUAL_BLOOD_GLUCOSE_ON_WATCH_DISABLED, eventual glucose on watch is not shown
* test with "temporary flag", no longer used: SHOW_EVENTUAL_BLOOD_GLUCOSE_ON_WATCH_ENABLED
* app builds
* eventual glucose shows on watch
=> reverse FeatureFlag logic for eventual glucose on watch

Loop/Extensions/UIAlertController.swift
Currently the availableCGMs are unsorted when the user taps the 'Add CGM' pill in UIAlertController, where they're sorted by LocalizedTitle when triggered from settings. 
This PR corrects this difference, making the CGMs easier to parse for new users.
Before:
After:
=> Adds sorting to AlertView-like dialog for adding a CGM

Loop/Managers/LoopDataManager.swift, Loop/Models/LoopError.swift, Loop/View Models/BolusEntryViewModel.swift, Loop/Views/BolusEntryView.swift, LoopCore/LoopCoreConstants.swift, LoopTests/ViewModels/BolusEntryViewModelTests.swift
This ~~is a work-in-progress~~ PR is in response to Issue #1890.
Configuration
* Test phone configured with future glucose and dosing strategy set to automatic bolus.
* Running dev, phone automatically boluses every 5 minutes, creating undesirable levels of IOB.
* With commit (updated to) fffcf505 of this branch, tested that the future glucose is detected and automated dosing stops
Display to User:
* Loop goes red over next 15 minutes, but need to add a better alerting system
* Tapping on glucose leads to the CGM
* Main screen continues to show the future glucose value (not CGM value)
* Tapping on bolus shows no recommendation with the new "Glucose in Future: Check for data in the future on phone" warning
* Tapping on meal entry allows the meal entry, but meal bolus screen is set for Save …
=> Prevent Automatic Dosing with Future Glucose

Loop.xcconfig, Loop/AppDelegate.swift, Loop/Info.plist
This PR defines a general URL scheme for opening Loop from other applications.  There is a config variable that defines the URL to use, which by default is the app's display name.  I'll submit a separate PR to LoopWorkspace with a placeholder override variable showing how to override that. 
There is skeleton code that extracts the rest of the URL so that URLs like "Loop://bolus" could be used to link to the Bolus view directly, but right now I'm unsure of the right place/method for doing that.  I thought I'd start by PR'ing this part to get started, and perhaps you could advise on next steps for the deeper links.
=> Open Loop with "Loop://" URLs from other applications

Loop.xcodeproj/project.pbxproj
Closes #1596 
It appears that the file **ckcomplication.strings** which is referenced [here](https://github.com/LoopKit/Loop/blob/71de4d05b1b18241e697d380078be6d0d3dc4f14/WatchApp%20Extension/Extensions/CLKComplicationTemplate.swift#L131) was [accidentally](https://loop.zulipchat.com/#narrow/stream/144111-general/topic/utilitarianlargeflat.20on.20watch/near/189617223) removed as apart of [this PR](https://github.com/LoopKit/Loop/commit/b4189bcae6a353398aeacf59276df1e98ef266fd#diff-f0aa8d568dbfc3e4be53b044c73a1d372fb8a8b8286b2f2d4afcc757b6da79b2L1344).
This would explain the issue reported in #1596.
Before
After
=> Re-add `ckcomplication.strings` to project manifest

Common/FeatureFlags.swift, Loop/Managers/ProfileExpirationAlerter.swift, Loop/Views/SettingsView.swift
Adding the ability for users to see when their profile expires without waiting for the pop-up warning modal message. 
This small enhancement gives users more visibility into the remaining life of their Loop app, to help them plan to rebuild and load fresh profiles.
\> 3 Days Dark
\> 3 Days Light 
< 3 Days Dark 
< 3 Days Light
=> Add profile expiration time to settings page

DoseMathTests/DoseMathTests.swift, Loop/Managers/DoseMath.swift, Loop/Managers/LoopDataManager.swift, Loop/Models/LoopError.swift, LoopTests/Managers/LoopDataManagerTests.swift, LoopTests/Mock Stores/MockCarbStore.swift, LoopTests/Mock Stores/MockDoseStore.swift, LoopTests/Mock Stores/MockGlucoseStore.swift, LoopTests/ViewModels/BolusEntryViewModelTests.swift
This replaces PR #1870.
This PR adds one safety check so that automatic dosing of insulin cannot exceed a simple ratio multiplied by a constant set in LoopConstants. It addresses the more critical portion of Issue #1863.
If this is deemed a good direction, there are some items to do:
* add proper logging
* report in the Delivery Limits section that the maximum of automatic delivery of insulin will be capped by the ratio times maxBolus to make it clear to the user
* decide what the correct ratio should be (1.2 was entered as a placeholder) - subsequently changed to 2.0.
=> Use maxBolus to set automaticDosingIOBLimit

Common/FeatureFlags.swift, Loop/Managers/DeviceDataManager.swift, Loop/Managers/LoopAppManager.swift, Loop/Managers/SettingsManager.swift
The build flag for disabling remote commands is misleading --  REMOTE_OVERRIDES_DISABLED -- as it more generally is used for disabling all commands (bolus and carbs). 
This PR will rename the flag to REMOTE_COMMANDS_DISABLED while continuing to support the old flag so users are not opted-into remote commands with this change.
I did some checks that building with both REMOTE_OVERRIDES_DISABLED and REMOTE_COMMANDS_DISABLED set disables remote commands.
=> Rename flag for disabling remote commands

Scripts/copy-plugins.sh
This PR aims to update the Loop codebase to accommodate Xcode 14.3 for successful archive preparation.
Currently, attempting to archive the Loop project using Xcode 14.3 results in the following error:
rsync error: some files could not be transferred (code 23) at /AppleInternal/Library/BuildRoots/97f6331a-ba75-11ed-a4bc-863efbbaf80d/Library/Caches/com.apple.xbs/Sources/rsync/rsync/main.c(996) [sender=2.6.9]
Command PhaseScriptExecution failed with a nonzero exit code
This PR incorporates the solution and background information outlined in the following post from TheLoopedGroup:
https://www.facebook.com/groups/TheLoopedGroup/posts/3354384161444893
The proposed changes have been tested and successfully resolved the archiving issue with Xcode 14.3.
=> Update Loop script to support Xcode 14.3 archiving

Loop/Managers/Missed Meal Detection/MealDetectionManager.swift, LoopTests/Managers/MealDetectionManagerTests.swift
This PR ensures the meal detection algorithm correctly converts mmol/L units into mg/dL when performing missed meal detection calculations.
[Associated LoopKit PR](https://github.com/LoopKit/LoopKit/pull/479)
=> Fix mmol unit conversion for missed meal detection

StatusWidget/StatusWidget.swift
Corrected calculation of time since last reading to restore delta readout on widget
=> BugFix: Show delta on Widget

Loop/Managers/LoopDataManager.swift, Loop/Models/LoopSettings+Loop.swift
This pull request solves the issue with toggling IRC On/Off without re-starting the app.
I did not want to re-create the RetrospectiveCorrection class for each evaluation or loop, therefore a new computed property retrospectiveCorrection is added in LoopDataManager. This property checks the integralRetrospectiveCorrectionEnabled flag in UserDefaults, and based on its state, it creates an instance of IntegralRetrospectiveCorrection or StandardRetrospectiveCorrection. This instance is then cached and reused unless the flag's value changes. 
Two new private variables, lastIntegralRetrospectiveCorrectionEnabled and cachedRetrospectiveCorrection, have been added to support the caching mechanism.
By removing the instance creation logic from the "Static configuration" block in LoopSettings, it …
=> Refactor RetrospectiveCorrection Initialization

Loop/Models/RetrospectiveCorrection/IntegralRetrospectiveCorrection.swift
This update mitigates the upward stacking of IRC and momentum effects, which may occur when retrospective correction is active and glucose is increasing rapidly, as [reported on Zulip](https://loop.zulipchat.com/#narrow/stream/144182-development/topic/Algorithm.20Experiments/near/376540452).
=> mitigate irc and momentum stacking

Loop Status Extension/StatusViewController.swift, Loop/Extensions/ChartColorPalette+Loop.swift, LoopUI/Charts/COBChart.swift, LoopUI/Charts/CarbEffectChart.swift, LoopUI/Charts/IOBChart.swift
In order to remove Caregiver's dependency on the Loop repo, I need to move certain charts from Loop to LoopKit. This PR will not move those charts yet but instead updates some chart APIs in prep for that.
* Use `ChartColorPalette` for chart colors: Charts use UIColor extension methods, like `insulinTintColor` which are not available in LoopKit. `ChartColorPalette` is available to LoopKit so this switches to using that. Additionally, I added `carbTint` to `ChartColorPalette` which was missing.
* Certain `HKUnit` extensions are not available to LoopKit. This will update the charts to use the `QuantityFormatter` for unit labels.
* This needs to merge with https://github.com/LoopKit/LoopKit/pull/498
=> Remove Loop Dependencies from Charts

Loop/Managers/LoopDataManager.swift, Loop/Models/PredictionInputEffect.swift, Loop/View Controllers/PredictionTableViewController.swift
Allows users to view the predicted effect of suspending insulin delivery on the Predicted Glucose screen. This is for information purposes only and does not affect dosing in any manner. An immediate use case is to assist users decide on their own if a carb correction might be needed to mitigate a potential low in the future. 
The Precited Glucose screen starts as usual, with only carbs, insulin, momentum, and retrospection enabled. 
In this example, an eventual glucose below the correction range is predicted. Manually selecting the Suspension of Insulin Delivery shows the effect and, in this case, shows that Loop should be able to easily correct the predicted glucose without the need for any carb corrections. 
Future (more ambitious) use cases for the effect of suspending insulin delivery …
=> add effect of suspending insulin delivery

Loop/Managers/DeviceDataManager.swift, Loop/Managers/LoopDataManager.swift
This is an attempt to fix the issue described here: https://github.com/LoopKit/Loop/issues/1919
It restricts triggering Loop when a CGMManager calls hasNew: multiple times in a row, as CGMBLEKit can do if it has a backfill error. Restricting the timer to only track *CGM* triggers allows us to still recover from a pump driven cycle. When just a Loop based time restriction was in place, it could cause this issue: https://github.com/LoopKit/Loop/issues/1817
=> Only trigger when new CGM data received > 4.2 minutes ago.

Loop/Views/IntegralRetrospectiveCorrectionSelectionView.swift
This PR fixes typos in the `IntegralRetrospectiveCorrectionSelectionView`.
See #2043 for details
=> ✏️  Fix a typo in IntegralRetrospectiveCorrectionSelectionView

Loop/View Models/CarbEntryViewModel.swift
After an override is complete, the warning that an override is enabled is still present in the carb entry screen (described in Zulip [here](https://loop.zulipchat.com/#narrow/stream/144182-development/topic/Active.20Override.20warning.20on.20Carb.20Entry)). I was not able to reproduce this issue, but still suspect that this change will fix it, as the new code now matches the [old UIKit code](https://github.com/LoopKit/Loop/blob/befcbcbe6733e52b315cb29904f7893e39da3514/Loop/View%20Controllers/CarbEntryViewController.swift#L242).
=> Override warning fix

Loop/View Controllers/InsulinDeliveryTableViewController.swift
Fixes #1968 
This fixes the issue of symbols appearing instead of numerals. Changes mainly affect Arabic but all numbers should be displayed correctly according to their language now.
=> Fixed numeral localization in insulin delivery table view

Common/hi.lproj/Intents.strings, Loop.xcodeproj/project.pbxproj
Addresses an issue where App Store Connect identifies missing Siri intents and sends an e-mail to GitHub builders to make them aware of the issue.
This is actively being discussed on Zulip:
https://loop.zulipchat.com/#narrow/stream/144182-development/topic/Translation.203.2E3.2E0/near/387480294
and
https://loop.zulipchat.com/#narrow/stream/144182-development/topic/Prep.20for.20Loop.203.2E4.20release.2E/near/390036388
=> Invalid Siri Support: Add Hindi Intents

Loop Widget Extension/Helpers/ContentMargin.swift, Loop Widget Extension/Helpers/WidgetBackground.swift, Loop Widget Extension/Widgets/SystemStatusWidget.swift, Loop.xcodeproj/project.pbxproj
Adds back Widget changes originally made for #2013 that were reserved to Xcode 15
=> Update widgets for build with Xcode 15

Loop/Managers/AppExpirationAlerter.swift
Now that some users of Browser Build method have profile expirations that are shorter than 90 days after the build, we see that the TestFlight expiration continues to be 90 days after build date.
In other words, TestFlight expiration is independent of profile expiration.
Remove the logic that considers profile expiration for a TestFlight build.
This has been tested with a Mac-Xcode build.
=> Fix logic error for TestFlight expiration

Loop/Managers/Alerts/StoredAlert.swift, LoopTests/Managers/Alerts/AlertStoreTests.swift, LoopTests/Managers/Alerts/StoredAlertTests.swift, LoopTests/ViewModels/BolusEntryViewModelTests.swift
This updates tests to run on iOS 17. But so far, there are issues running iOS 17 simulators on circleci and github.
=> Updates to tests for iOS 17

Common/Models/BuildDetails.swift, Scripts/capture-build-details.sh
Xcode now stores the provisioning profile in a new location, which renders the hardcoded path in Scripts/capture-build-details.sh ineffective. This PR resolves the issue by reading the provisioning profile at runtime and storing it in a cached constant within the BuildDetails class.
Example of expire date using Xcode 16 and iOS 18.
=> Provisioning profile support for Xcode 16

Loop/View Controllers/StatusTableViewController.swift
This PR fixes an intermittent bolus progress display error reported in these issues
* #2196
* #2195
* #2109
@itsmojo identified root cause for this intermittent display error and passed on a proposed fix for the `main` branch which is found in this PR.
> If a bolus progress is being displayed when the app is put into background and then the app is opened in the middle of a bolus, the progress bar shows a stale value of the expected total units; the stale value is the total units from the last time the bolus progress bar was displayed.
This PR is one of 3. One each to main (closed), tidepool-merge (open) and dev (this one).
The all have the same fix which has been tested extensively.
=> update progressCell for bolus display

Loop/Views/GlucoseBasedApplicationFactorSelectionView.swift, Loop/Views/IntegralRetrospectiveCorrectionSelectionView.swift, Loop/Views/SettingsView+algorithmExperimentsSection.swift
Purpose: this fix a display issue whereby changing an Algorithm Experiment then backing out from Algorithm experiments section and back in (without closing settings) results in the data being displayed as it initially appeared. This issue is mentioned in this comment (https://github.com/LoopKit/Loop/issues/2267#issuecomment-2567019786) - note that issue 2267 (which also has similar behavior in terms of a view not being updated despite the underlying data being saved) is however unrelated and thus this PR doesn't address it.
This is caused by the view being discarded from the render tree and then being restored as it was initialized.
This fix addresses this and cleans up the code as well by using AppStorage - the selection views themselves then only work with the Bindings and not directly …
=> Force reload from UserDefaults

Loop/View Controllers/StatusTableViewController.swift
This PR fixes an intermittent bolus progress display error reported in these issues
* #2196
* #2195
* #2109
@itsmojo identified root cause for this intermittent display error and passed on a proposed fix for the `main` branch.
> If a bolus progress is being displayed when the app is put into background and then the app is opened in the middle of a bolus, the progress bar shows a stale value of the expected total units; the stale value is the total units from the last time the bolus progress bar was displayed.
I tested the `tidepool-merge` build using this [test method](https://github.com/LoopKit/Loop/issues/2196#issuecomment-2479431845) and showed the intermittent display error occurs with `tidepool-merge` as well as `main`. The fix from @itsmojo was modified to work with the new …
=> update progressCell for bolus display for tidepool-merge

Loop/Views/GlucoseBasedApplicationFactorSelectionView.swift, Loop/Views/IntegralRetrospectiveCorrectionSelectionView.swift, Loop/Views/SettingsView+algorithmExperimentsSection.swift
Previous PR #2279 was accidentally merged while pointing to the `main` branch.
That PR referred to Issue #2267. However, Issue #2267 is actually fixed with [LoopKit PR 555](https://github.com/LoopKit/LoopKit/pull/555).
This PR properly points to the `dev` branch and makes the same code change as 2279.
This PR fixes an issue where the algorithm experiment settings displayed may be stale.
> This is caused by the view being discarded from the render tree and then being restored as it was initialized.
> This fix addresses this and cleans up the code as well by using AppStorage - the selection views themselves then only work with the Bindings and not directly with UserDefaults.
=> Force reload from UserDefaults for Algorithm Experiments

Loop/View Controllers/StatusTableViewController.swift
This PR should resolve Issue #2196.
I failed to test PR #2295, which was supposed to resolve the issue, in a LoopWorkspace build.
As explained [here](https://github.com/LoopKit/Loop/pull/2295#issuecomment-2745521527), I was given a version of the patch that worked with `dev`, but had to modify it for tidepool-merge.
The dev branch of LoopWorkspace is still pointing to an earlier commit for Loop, so my mistake in PR 2295 does not affect LoopWorkspace dev.
With the addition of this PR to Loop dev (commit 710182e2, resultant commit prior to merge: 46f7a49d):
* building LoopWorkspace to a phone simulator succeeds
* running the Tests all succeed
My next comment will cover testing using a Test Phone to demonstrate the UI glitch is resolved.
=> update progressCell for bolus display, finish update for dev branch

Loop/Managers/SupportManager.swift, Version.xcconfig
Simplify release process
* add a version number file to the LoopWorkspace folder and point to it from Version.xcconfig in the Loop folder
* this requires coordinated PR for Loop and LoopWorkspace
The Version.xcconfig file in the Loop repository is modified to point to the new file, LoopVersion.xcconfig, in the LoopWorkspace repository.
The [LoopWorkspace PR 241](https://github.com/LoopKit/LoopWorkspace/pull/241) requires an update to the new Loop SHA after this PR is merged.
=> Configure the version number in LoopWorkspace, not Loop

Common/Models/BuildDetails.swift, Scripts/capture-build-details.sh
Make a new PR to `tidepool-merge` branch parallel to the one provided for `dev` branch.
See PR #2241 for full reference information.
In summary:
* Reverted Common/Models/BuildDetails.swift to its state before the “xcode16_profile_support” merge.
* Updated Scripts/capture-build-details.sh to search for .mobileprovision files in both Xcode 15.4 and Xcode 16 locations.
This was tested previously when testing [LoopWorkspace PR 214](https://github.com/LoopKit/LoopWorkspace/pull/214) but not with a formal branch that could be used as a PR.
=> tidepool-merge: Adjust provisioning profile path in script for Xcode 16 compatibility

Loop/View Controllers/CarbAbsorptionViewController.swift
The 'predicted' dataset on the 'glucose change' graph was calculated using insulin counteraction effects that had been truncated to the width of the chart. This meant that carb entries early in the timeline may not have dynamic carb absorption applied as the implied ICE was zero for the first part of the carb entry's history.
Addresses the different behaviour in landscape and portrait view of the glucose change graph in the carbohydrate screen. so that dynamic carb effects are always shown when they are in effect.
For discussion (but not included in this pull request), for clarity the graph dataset label could be changed from 'Predicted' to 'Estimated and predicted' given that it already incorporates dynamic glucose effects (when these are in effect), so is partly based on observation. …
=> Use full ICE history for displaying estimated carbohydrate effects

Loop/Views/BolusEntryView.swift, Loop/Views/SimpleBolusView.swift
Provide a different label for the button when saving carbs and bolusing to make it more obvious that tapping the button saves the carbs.
See Issue #2168 for explanation.
Not understanding that carbs are saved even if bolus is not successful is a problem experienced by many new loopers and often by new caregivers for younger loopers.
=> Update meal label, proposed remedy for Issue #2168
